sudo: required

branches:
  only:
    - 1.7.1

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull htakeuchi/docker-asciidoctor-jp

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html htakeuchi/docker-asciidoctor-jp asciidoctor -D /documents/output *.asciidoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf htakeuchi/docker-asciidoctor-jp asciidoctor-pdf  -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicJP -D /documents/output *.asciidoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:
  - cd output ; mv README.html index.html ; cp -R ../images images
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1